import { translate } from 'google-translate-nodejs'

const LANGUAGES = [
    { code: "abk", lang: "abkhaz", language: "abkhaz" },
    { code: "ace", lang: "acehnese", language: "bahasa aceh" },
    { code: "ach", lang: "acholi", language: "acholi" },
    { code: "aa", lang: "afar", language: "afar" },
    { code: "af", lang: "afrikaans", language: "afrikaans" },
    { code: "sq", lang: "albanian", language: "shqip" },
    { code: "alz", lang: "alur", language: "Dhu'alur" },
    { code: "am", lang: "amharic", language: "አማርኛ" },
    { code: "ar", lang: "arabic", language: "عربي" },
    { code: "hy", lang: "armenian", language: "հայ" },
    { code: "as", lang: "assamese", language: "অসমীয়া" },
    { code: "ava", lang: "avar", language: "avar" },
    { code: "awa", lang: "awadhi", language: "अवधी" },
    { code: "ay", lang: "aymara", language: "Aymara" },
    { code: "az", lang: "azerbaijani", language: "azərbaycanlı" },
    { code: "ban", lang: "balinese", language: "Basa Bali" },
    { code: "bal", lang: "baluchi", language: "بلوچی" },
    { code: "bm", lang: "bambara", language: "Bamanankan" },
    { code: "bci", lang: "baoulé", language: "Wawle" },
    { code: "bak", lang: "bashkir", language: "bashkir" },
    { code: "eu", lang: "basque", language: "euskalduna" },
    { code: "btx", lang: "batak karo", language: "Batak Karo" },
    { code: "bts", lang: "batak simalungun", language: "Bahasa Simalungun" },
    { code: "bbc", lang: "batak toba", language: "Batak Toba" },
    { code: "be", lang: "belarusian", language: "беларускі" },
    { code: "bem", lang: "bemba", language: "Ichibemba" },
    { code: "bn", lang: "bengali", language: "বাংলা" },
    { code: "bew", lang: "betawi", language: "Betawi" },
    { code: "bho", lang: "bhojpuri", language: "भोजपुरी" },
    { code: "bik", lang: "bikol", language: "bikol" },
    { code: "bs", lang: "bosnian", language: "bosanski" },
    { code: "bre", lang: "breton", language: "breton" },
    { code: "bg", lang: "bulgarian", language: "български" },
    { code: "bua", lang: "buryat", language: "Буряад" },
    { code: "yue", lang: "cantonese", language: "廣州話" },
    { code: "ca", lang: "catalan", language: "català" },
    { code: "ceb", lang: "cebuano", language: "Cebuano" },
    { code: "cha", lang: "chamorro", language: "chamorro" },
    { code: "che", lang: "chechen", language: "chechen" },
    { code: "zh", lang: "chinese", language: "中国人" },
    { code: "zh-cn", lang: "chinese (simplified)", language: "中文（简体）" },
    { code: "zh-tw", lang: "chinese (traditional)", language: "中文（繁體）" },
    { code: "chk", lang: "chuukese", language: "Trukese" },
    { code: "chv", lang: "chuvash", language: "chuvash" },
    { code: "co", lang: "corsican", language: "Corsu" },
    { code: "crh", lang: "crimean tatar", language: "Къырымтатар" },
    { code: "hr", lang: "croatian", language: "hrvatski" },
    { code: "cs", lang: "czech", language: "čeština" },
    { code: "da", lang: "danish", language: "dansk" },
    { code: "fa-af", lang: "dari", language: "دری" },
    { code: "dv", lang: "dhivehi", language: "ދިވެހި" },
    { code: "din", lang: "dinka", language: "Dinka" },
    { code: "doi", lang: "dogri", language: "डोगरी" },
    { code: "dom", lang: "dombe", language: "dombe" },
    { code: "nl", lang: "dutch", language: "Nederlands" },
    { code: "dyu", lang: "dyula", language: "Julakan" },
    { code: "dzo", lang: "dzongkha", language: "dzongkha" },
    { code: "en", lang: "english", language: "english" },
    { code: "eo", lang: "esperanto", language: "esperanto" },
    { code: "et", lang: "estonian", language: "eesti keel" },
    { code: "fao", lang: "faroese", language: "faroese" },
    { code: "fij", lang: "fijian", language: "fijian" },
    { code: "fil", lang: "filipino (tagalog)", language: "filipino (tagalog)" },
    { code: "fi", lang: "finnish", language: "suomeksi" },
    { code: "fon", lang: "fon", language: "fongbē" },
    { code: "fr", lang: "french", language: "Français" },
    { code: "fy", lang: "frisian", language: "frysk" },
    { code: "fur", lang: "friulian", language: "Furlan" },
    { code: "ful", lang: "fulani", language: "fulani" },
    { code: "gaa", lang: "ga", language: "ga" },
    { code: "gl", lang: "galician", language: "galego" },
    { code: "ka", lang: "georgian", language: "ქართველი" },
    { code: "de", lang: "german", language: "Deutsch" },
    { code: "el", lang: "greek", language: "ελληνικά" },
    { code: "gn", lang: "guarani", language: "guarani" },
    { code: "gu", lang: "gujarati", language: "ગુજરાતી" },
    { code: "ht", lang: "haitian creole", language: "kreyol ayisyen" },
    { code: "cnh", lang: "hakha chin", language: "Lai holh" },
    { code: "ha", lang: "hausa", language: "hausa" },
    { code: "haw", lang: "hawaiian", language: "ʻŌlelo Hawaiʻi" },
    { code: "iw", lang: "hebrew", language: "עִברִית" },
    { code: "hil", lang: "hiligaynon", language: "Hiligaynon" },
    { code: "hi", lang: "hindi", language: "हिन्दी" },
    { code: "hmn", lang: "hmong", language: "hmoob" },
    { code: "hu", lang: "hungarian", language: "magyar" },
    { code: "hrx", lang: "hunsrik", language: "Hunsrik" },
    { code: "iba", lang: "iban", language: "Iban" },
    { code: "is", lang: "icelandic", language: "íslensku" },
    { code: "ig", lang: "igbo", language: "igbo" },
    { code: "ilo", lang: "ilocano", language: "Ilocano" },
    { code: "id", lang: "indonesian", language: "Indonesia" },
    { code: "ga", lang: "irish", language: "gaeilge" },
    { code: "it", lang: "italian", language: "italiano" },
    { code: "jam", lang: "jamaican patois", language: "jamaican patois" },
    { code: "ja", lang: "japanese", language: "日本語" },
    { code: "jw", lang: "javanese", language: "basa jawa" },
    { code: "kac", lang: "jingpo", language: "Jingpo" },
    { code: "kal", lang: "kalaallisut", language: "kalaallisut" },
    { code: "kn", lang: "kannada", language: "ಕನ್ನಡ" },
    { code: "kau", lang: "kanuri", language: "kanuri" },
    { code: "pam", lang: "kapampangan", language: "kapampangan" },
    { code: "kk", lang: "kazakh", language: "қазақ" },
    { code: "kha", lang: "khasi", language: "khasi" },
    { code: "km", lang: "khmer", language: "ខ្មែរ" },
    { code: "cgg", lang: "kiga", language: "Kiga" },
    { code: "kik", lang: "kikongo", language: "kikongo" },
    { code: "rw", lang: "kinyarwanda", language: "kinyarwanda" },
    { code: "ktu", lang: "kituba", language: "Kituba" },
    { code: "trp", lang: "kokborok", language: "Kok Borok" },
    { code: "kom", lang: "komi", language: "komi" },
    { code: "gom", lang: "konkani", language: "कोंकणी" },
    { code: "ko", lang: "korean", language: "한국인" },
    { code: "kri", lang: "krio", language: "Krio" },
    { code: "ku", lang: "kurdish", language: "Kurdî" },
    { code: "ckb", lang: "kurdish (sorani)", language: "کوردی (سۆرانی)" },
    { code: "ky", lang: "kyrgyz", language: "Кыргызча" },
    { code: "lo", lang: "lao", language: "ລາວ" },
    { code: "ltg", lang: "latgalian", language: "latgalīšu" },
    { code: "la", lang: "latin", language: "latin" },
    { code: "lv", lang: "latvian", language: "latviski" },
    { code: "lij", lang: "ligurian", language: "Ligure" },
    { code: "lim", lang: "limburgish", language: "limburgish" },
    { code: "ln", lang: "lingala", language: "Lingala" },
    { code: "lt", lang: "lithuanian", language: "lietuvis" },
    { code: "lmo", lang: "lombard", language: "Lombard" },
    { code: "lg", lang: "luganda", language: "Oluganda" },
    { code: "luo", lang: "luo", language: "Luo" },
    { code: "lb", lang: "luxembourgish", language: "lëtzebuergesch" },
    { code: "mk", lang: "macedonian", language: "македонски" },
    { code: "mad", lang: "madurese", language: "Madurâ" },
    { code: "mai", lang: "maithili", language: "मैथिली" },
    { code: "mak", lang: "makassar", language: "makassar" },
    { code: "mg", lang: "malagasy", language: "malagasy" },
    { code: "ms", lang: "malay", language: "melayu" },
    { code: "ms-arab", lang: "malay (jawi)", language: "melayu (jawi)" },
    { code: "ml", lang: "malayalam", language: "മലയാളം" },
    { code: "mt", lang: "maltese", language: "malti" },
    { code: "mam", lang: "mam", language: "toj qyol" },
    { code: "glv", lang: "manx", language: "manx" },
    { code: "mi", lang: "maori", language: "maori" },
    { code: "mr", lang: "marathi", language: "मराठी" },
    { code: "mah", lang: "marshallese", language: "marshallese" },
    { code: "mwr", lang: "marwadi", language: "मारवाड़ी" },
    { code: "mfe", lang: "mauritian creole", language: "kreol morisien" },
    { code: "mhr", lang: "meadow mari", language: "Мари шалбаасы" },
    { code: "mni-mtei", lang: "meiteilon (manipuri)", language: "ꯃꯦꯏꯇꯦꯏꯂꯣꯟ (ꯃꯅꯤꯄꯨꯔꯤ)" },
    { code: "min", lang: "minang", language: "minang" },
    { code: "lus", lang: "mizo", language: "Mizo tawng" },
    { code: "mn", lang: "mongolian", language: "монгол" },
    { code: "my", lang: "myanmar (burmese)", language: "မြန်မာ (ဗမာ)" },
    { code: "nhe", lang: "nahuatl (eastern huasteca)", language: "nahuatl (huasteca oriental)" },
    { code: "ndc-zw", lang: "ndau", language: "ndau" },
    { code: "nde", lang: "ndebele (south)", language: "ndebele (south)" },
    { code: "new", lang: "nepalbhasa (newari)", language: "नेपालभाषा (नेवारी) ३." },
    { code: "ne", lang: "nepali", language: "नेपाली" },
    { code: "no", lang: "norwegian", language: "norsk" },
    { code: "nus", lang: "nuer", language: "Thok Nath" },
    { code: "ny", lang: "nyanja (chichewa)", language: "nyanja (chichewa)" },
    { code: "oci", lang: "occitan", language: "occitan" },
    { code: "or", lang: "odia (oriya)", language: "odia (oriya)" },
    { code: "om", lang: "oromo", language: "Afaan Oromoo" },
    { code: "oss", lang: "ossetian", language: "ossetian" },
    { code: "pag", lang: "pangasinan", language: "Pangasinan" },
    { code: "pap", lang: "papiamento", language: "Papiamentu" },
    { code: "ps", lang: "pashto", language: "پښتو" },
    { code: "fa", lang: "persian", language: "فارسی" },
    { code: "pl", lang: "polish", language: "polski" },
    { code: "por", lang: "portuguese (portugal)", language: "portuguese (portugal)" },
    { code: "pt", lang: "portuguese (portugal, brazil)", language: "português (portugal, brasil)" },
    { code: "pa", lang: "punjabi", language: "ਪੰਜਾਬੀ" },
    { code: "pa-arab", lang: "punjabi (shahmukhi)", language: "ਪੰਜਾਬੀ (ਸ਼ਾਹਮੁਖੀ)" },
    { code: "kek", lang: "q'eqchi'", language: "q'eqchi'." },
    { code: "qu", lang: "quechua", language: "Runasimi" },
    { code: "rom", lang: "romani", language: "Rromani ćhib" },
    { code: "ro", lang: "romanian", language: "română" },
    { code: "run", lang: "rundi", language: "rundi" },
    { code: "ru", lang: "russian", language: "русский" },
    { code: "sme", lang: "sami (north)", language: "sami (north)" },
    { code: "sm", lang: "samoan", language: "samoa" },
    { code: "sag", lang: "sango", language: "sango" },
    { code: "sa", lang: "sanskrit", language: "संस्कृत" },
    { code: "sat", lang: "santali", language: "ᱥᱟᱱᱛᱟᱲᱤ" },
    { code: "gd", lang: "scots gaelic", language: "Gàidhlig na h-Alba" },
    { code: "nso", lang: "sepedi", language: "Sepedi" },
    { code: "sr", lang: "serbian", language: "српски" },
    { code: "st", lang: "sesotho", language: "sesotho" },
    { code: "crs", lang: "seychellois creole", language: "kreol Seselwa" },
    { code: "shn", lang: "shan", language: "တႆး" },
    { code: "sn", lang: "shona", language: "shona" },
    { code: "scn", lang: "sicilian", language: "Sicilianu" },
    { code: "szl", lang: "silesian", language: "Ślōnski" },
    { code: "sd", lang: "sindhi", language: "سنڌي" },
    { code: "si", lang: "sinhala (sinhalese)", language: "සිංහල (සිංහල)" },
    { code: "sk", lang: "slovak", language: "slovenčina" },
    { code: "sl", lang: "slovenian", language: "slovenščina" },
    { code: "so", lang: "somali", language: "somaliyeed" },
    { code: "es", lang: "spanish", language: "español" },
    { code: "su", lang: "sundanese", language: "basa sunda" },
    { code: "sus", lang: "susu", language: "Sosokhui" },
    { code: "sw", lang: "swahili", language: "kiswahili" },
    { code: "ssw", lang: "swati", language: "swati" },
    { code: "sv", lang: "swedish", language: "svenska" },
    { code: "tl", lang: "tagalog (filipino)", language: "tagalog (filipino)" },
    { code: "tah", lang: "tahitian", language: "tahitian" },
    { code: "tg", lang: "tajik", language: "тоҷикӣ" },
    { code: "ber-atn", lang: "tamazight", language: "tamazight" },
    { code: "ber", lang: "tamazight (tifinagh)", language: "ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵜⵉⴼⵉⵏⴰⵖ)" },
    { code: "ta", lang: "tamil", language: "தமிழ்" },
    { code: "tt", lang: "tatar", language: "татар" },
    { code: "te", lang: "telugu", language: "తెలుగు" },
    { code: "tet", lang: "tetum", language: "Tetun" },
    { code: "th", lang: "thai", language: "แบบไทย" },
    { code: "bod", lang: "tibetan", language: "tibetan" },
    { code: "ti", lang: "tigrinya", language: "ትግሪኛ" },
    { code: "tiv", lang: "tiv", language: "Tiv" },
    { code: "tpi", lang: "tok pisin", language: "Tok Pisin" },
    { code: "ton", lang: "tongan", language: "tongan" },
    { code: "ts", lang: "tsonga", language: "Tsonga" },
    { code: "tsn", lang: "tswana", language: "tswana" },
    { code: "tcy", lang: "tulu", language: "ತುಳು" },
    { code: "tum", lang: "tumbuka", language: "Tumbuka" },
    { code: "tr", lang: "turkish", language: "Türkçe" },
    { code: "tk", lang: "turkmen", language: "türkmen" },
    { code: "tuk", lang: "tuvan", language: "tuvan" },
    { code: "ak", lang: "twi (akan)", language: "twi (akan) ." },
    { code: "udm", lang: "udmurt", language: "Удмурт кыл" },
    { code: "uk", lang: "ukrainian", language: "українська" },
    { code: "ur", lang: "urdu", language: "اردو" },
    { code: "ug", lang: "uyghur", language: "uyghur" },
    { code: "uz", lang: "uzbek", language: "o'zbek" },
    { code: "ven", lang: "venda", language: "venda" },
    { code: "vec", lang: "venetian", language: "Veneto" },
    { code: "vi", lang: "vietnamese", language: "tiếng việt" },
    { code: "war", lang: "waray", language: "Waray" },
    { code: "cy", lang: "welsh", language: "cymraeg" },
    { code: "wol", lang: "wolof", language: "wolof" },
    { code: "xh", lang: "xhosa", language: "isiXhosa" },
    { code: "sah", lang: "yakut", language: "Саха" },
    { code: "yi", lang: "yiddish", language: "ייִדיש" },
    { code: "yo", lang: "yoruba", language: "yoruba" },
    { code: "yua", lang: "yucatec maya", language: "yucatec maya" },
    { code: "zap", lang: "zapotec", language: "Diidxazá" },
    { code: "zu", lang: "zulu", language: "zulu" }
]

const ETHIOPIAN_Languages = LANGUAGES.filter(lang =>
  ['amharic', 'oromo', 'somali', 'tigrinya', 'afar', 'english'].includes(lang.lang)
)

export const getAllLanguages = async (req, res, next) => {
    res.status(200).json(LANGUAGES)
}

export const getEthiopianLanguages = async (req, res, next) => {
    res.status(200).json(ETHIOPIAN_Languages)
}

export const textTranslators = async (req, res, next) => {
    const { text, to } = req.body
    const response = await translate.single(text, to)
    res.status(200).json({data: response.data.target})    
}